### ISSUE TITLE
Exceptions in jaxb unmarshalling are not being handled correctly

### ISSUE THREAD

**Issue by at055612** [gchq/stroom-stats#28]
The error is caused because stroom is sending an old xml format.  This exception needs to be handled by putting the message on the bad topic

```ERROR  [12:10:24.439] [StreamThread-4] s.s.s.StatisticsFlatMappingProcessor -  Uncaught exception in stream processor with appId FlatMapProcessor-Value type VALUE and mapper ValueStatToAggregateFlatMapper in thread StreamThread-4 
java.lang.RuntimeException: Errors encountered un-marshalling xml: unexpected element (uri:"statistics:3", local:"name"). Expected elements are <{statistics:3}count>,<{statistics:3}time>,<{statistics:3}value>,<{statistics:3}key>,<{statistics:3}tags>,<{statistics:3}identifiers> at line 1 col 106
	at stroom.stats.schema.v3.StatisticsMarshaller.unMarshallFromXml(StatisticsMarshaller.java:77)
	at org.apache.kafka.streams.kstream.internals.KStreamMapValues$KStreamMapProcessor.process(KStreamMapValues.java:41)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:68)
	at org.apache.kafka.streams.processor.internals.StreamTask.forward(StreamTask.java:343)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:187)
	at org.apache.kafka.streams.kstream.internals.KStreamFilter$KStreamFilterProcessor.process(KStreamFilter.java:44)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:68)
	at org.apache.kafka.streams.processor.internals.StreamTask.forward(StreamTask.java:343)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:187)
	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:64)
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:174)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:320)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:218)```

**Comment by at055612** [comment]
Suggest we have an initial map operation that attempts to unmarshall the xml string into a jaxb object and wrap that object in another class. That wrapper class can contain the jaxb object, the raw string and any exception.  Then we can have a branch step to move wrappers that have an exception in to the bad topic.
