### ISSUE TITLE
NPE when searching with no fields in the table

### ISSUE THREAD

**Issue by at055612** [gchq/stroom-stats#37]
```ERROR  [16:18:22.096] [dw-55 - POST /api/stroom-stats/v2/search] s.s.s.r.q.v.QueryResource -  Error processing web service request 
java.lang.NullPointerException: null
	at stroom.query.common.v2.CompiledFields.<init>(CompiledFields.java:37)
	at stroom.query.common.v2.TableCoprocessor.<init>(TableCoprocessor.java:43)
	at stroom.stats.HBaseClient.createCoprocessor(HBaseClient.java:326)
	at stroom.stats.HBaseClient.performSearch(HBaseClient.java:177)
	at stroom.stats.HBaseClient.lambda$query$0(HBaseClient.java:143)
	at java.util.Optional.map(Optional.java:215)
	at stroom.stats.HBaseClient.query(HBaseClient.java:142)```

**Comment by at055612** [comment]
See also the same issue with sql stats in stroom https://github.com/gchq/stroom/issues/412

**Comment by at055612** [comment]
I think stroom-query just needs the following in CompileFields.java
```    
public CompiledFields(final List<Field> fields,
                          final FieldIndexMap fieldIndexMap, final Map<String, String> paramMap) {
        compiledFields = new ArrayList<>(fields == null ? 0 : fields.size());
        if (fields != null) {
            final ExpressionParser expressionParser = new ExpressionParser(new FunctionFactory(), new ParamFactory());
            for (final Field field : fields) {
...
        }
```
But fixing that may lead to other NPEs in stroom-query
