### ISSUE TITLE
NoResultException when processing stats

### ISSUE THREAD

**Issue by at055612** [gchq/stroom-stats#40]
```
stroom-stats       | ERROR  [15:07:32.694] [StreamThread-2] s.s.s.StatisticsFlatMappingProcessor -  Uncaught exception in stream processor with appId FlatMapProcessor-Count type COUNT and mapper CountStatToAggregateFlatMapper in thread StreamThread-2 
stroom-stats       | java.lang.RuntimeException: Error executing task, javax.persistence.NoResultException: No entity found for query
stroom-stats       |    at stroom.stats.configuration.StatisticConfigurationServiceImpl.executeInSession(StatisticConfigurationServiceImpl.java:86)
stroom-stats       |    at stroom.stats.configuration.StatisticConfigurationServiceImpl.fetchStatisticConfigurationByUuid(StatisticConfigurationServiceImpl.java:73)
stroom-stats       |    at stroom.stats.streams.StatisticsFlatMappingStreamFactory.buildStatisticWrapper(StatisticsFlatMappingStreamFactory.java:272)
stroom-stats       |    at org.apache.kafka.streams.kstream.internals.KStreamMap$KStreamMapProcessor.process(KStreamMap.java:42)
stroom-stats       |    at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:68)
stroom-stats       |    at org.apache.kafka.streams.processor.internals.StreamTask.forward(StreamTask.java:343)
stroom-stats       |    at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:187)
stroom-stats       |    at org.apache.kafka.streams.kstream.internals.KStreamFlatMapValues$KStreamFlatMapValuesProcessor.process(KStreamFlatMapValues.java:43)
stroom-stats       |    at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:68)
stroom-stats       |    at org.apache.kafka.streams.processor.internals.StreamTask.forward(StreamTask.java:343)
stroom-stats       |    at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:187)
stroom-stats       |    at org.apache.kafka.streams.kstream.internals.KStreamPassThrough$KStreamPassThroughProcessor.process(KStreamPassThrough.java:34)
stroom-stats       |    at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:68)
stroom-stats       |    at org.apache.kafka.streams.processor.internals.StreamTask.forward(StreamTask.java:356)
stroom-stats       |    at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:192)
stroom-stats       |    at org.apache.kafka.streams.kstream.internals.KStreamBranch$KStreamBranchProcessor.process(KStreamBranch.java:46)
stroom-stats       |    at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:68)
stroom-stats       |    at org.apache.kafka.streams.processor.internals.StreamTask.forward(StreamTask.java:343)
stroom-stats       |    at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:187)
stroom-stats       |    at org.apache.kafka.streams.kstream.internals.KStreamMapValues$KStreamMapProcessor.process(KStreamMapValues.java:42)
stroom-stats       |    at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:68)
stroom-stats       |    at org.apache.kafka.streams.processor.internals.StreamTask.forward(StreamTask.java:343)
stroom-stats       |    at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:187)
stroom-stats       |    at org.apache.kafka.streams.kstream.internals.KStreamFilter$KStreamFilterProcessor.process(KStreamFilter.java:44)
stroom-stats       |    at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:68)
stroom-stats       |    at org.apache.kafka.streams.processor.internals.StreamTask.forward(StreamTask.java:343)
stroom-stats       |    at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:187)
stroom-stats       |    at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:64)
stroom-stats       |    at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:174)
stroom-stats       |    at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:320)
stroom-stats       |    at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:218)
stroom-stats       | Caused by: org.ehcache.spi.loaderwriter.CacheLoadingException: javax.persistence.NoResultException: No entity found for query
stroom-stats       |    at org.ehcache.core.exceptions.ExceptionFactory.newCacheLoadingException(ExceptionFactory.java:48)
stroom-stats       |    at org.ehcache.core.EhcacheWithLoaderWriter$2.apply(EhcacheWithLoaderWriter.java:226)
stroom-stats       |    at org.ehcache.core.internal.util.Functions$MemoizingFunction.apply(Functions.java:71)
stroom-stats       |    at org.ehcache.impl.internal.store.heap.OnHeapStore$23.apply(OnHeapStore.java:1228)
stroom-stats       |    at org.ehcache.impl.internal.store.heap.OnHeapStore$23.apply(OnHeapStore.java:1220)
stroom-stats       |    at org.ehcache.impl.internal.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1878)
stroom-stats       |    at org.ehcache.impl.internal.store.heap.SimpleBackend.compute(SimpleBackend.java:96)
stroom-stats       |    at org.ehcache.impl.internal.store.heap.OnHeapStore.computeIfAbsent(OnHeapStore.java:1220)
stroom-stats       |    at org.ehcache.core.EhcacheWithLoaderWriter.get(EhcacheWithLoaderWriter.java:234)
stroom-stats       |    at stroom.stats.configuration.StatisticConfigurationServiceImpl.lambda$fetchStatisticConfigurationByUuid$1(StatisticConfigurationServiceImpl.java:74)
stroom-stats       |    at stroom.stats.configuration.StatisticConfigurationServiceImpl.executeInSession(StatisticConfigurationServiceImpl.java:84)
stroom-stats       |    ... 30 common frames omitted
stroom-stats       | Caused by: javax.persistence.NoResultException: No entity found for query
stroom-stats       |    at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1461)
stroom-stats       |    at stroom.stats.configuration.StroomStatsStoreEntityDAOImpl.loadByUuid(StroomStatsStoreEntityDAOImpl.java:62)
stroom-stats       |    at stroom.stats.configuration.StatisticConfigurationCacheByUuidLoaderWriter.load(StatisticConfigurationCacheByUuidLoaderWriter.java:46)
stroom-stats       |    at stroom.stats.configuration.StatisticConfigurationCacheByUuidLoaderWriter.load(StatisticConfigurationCacheByUuidLoaderWriter.java:29)
stroom-stats       |    at org.ehcache.core.EhcacheWithLoaderWriter$2.apply(EhcacheWithLoaderWriter.java:222)
stroom-stats       |    ... 39 common frames omitted
```

**Comment by at055612** [comment]
Need to catch the NoResultException and return an empty Optional in the DAOImpl class.

Also need to figure out why the uuid is not there.  This was seen when processing the COUNT_SMALL test data when both stroom and -stats were running in docker.  Need better logging to see what UUID is being queried for.
